
# Spring Boot JWT Authentication
POST {{host}}:{{port}}/login
Content-Type: application/json

{
    "username": "HkevinH",
    "password": "kl3196704@gmail.com"
}


### Create User
POST {{host}}:{{port}}/register
Content-Type: application/json

{
    "id": 0,
    "username": "test",
    "password": "test",
    "email": "test@gmail.com",
    "role": "user",
    "token" : "eyJhbGci",
    "active" : 1
}


### Create Update User
POST {{host}}:{{port}}/update/user
Content-Type: application/json

{
  "id": 0,
  "username": "benitoperez01",
  "password": "test",
  "email": "test@gmail.com",
  "role": "teacher",
  "token" : "eyJhbGci",
  "active" : 1
}


### Get All Users

GET {{host}}:{{port}}/getAllUsers


### Delete User By Id

DELETE {{host}}:{{port}}/users/delete/0


### Get User Oauth2

GET {{host}}:{{port}}/user/oauth